### ISSUE TITLE
Error when trying to launch erocci-dbus-java

### ISSUE THREAD

**Issue by ffringel** [occiware/erocci-dbus-java#24] opened 2016-03-28 12:34 UTC
Hi @jeanparpaillon ,
I get the following error when trying to launch erocci-dbus-java. I would love your help on the issue

[ERROR] Failed to execute goal on project erocci-dbus-java: Could not resolve dependencies for project org.occiware.erocci.java:erocci-dbus-java:jar:0.2-SNAPSHOT: Could not find artifact com.github.docker-java:docker-java:jar:3.0.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jeanparpaillon** [comment] 2016-03-29 07:41
I think it is a duplicate of #23

**Comment by cgourdin** [comment] 2016-03-29 08:36
Hello, have you tried to launch this shell script before : ./dbus-java-install-script.sh  ?
I will make an update of maven pom this week to declare dependencies in a maven local repo like that is explain here : http://mark.koli.ch/maven-add-local-jar-dependency-to-classpath
Please note that some dependencies doesn't have a maven repo.

**Comment by ffringel** [comment] 2016-03-29 09:06
Thanks

**Comment by cgourdin** [comment] 2016-03-29 13:58
There was one dependency missing, this should be resolved for this error (at least, you must execute dbus-java-install-script.sh to install local dependencies in local maven repo), I didn't succeed to process with maven plugins to install local jars with maven-install-plugin, i will do more searching for usage with maven pom in place of shell scripts (mvn install:install-file).

**Comment by cgourdin** [comment] 2016-03-31 11:41
For building you must :
launch shell script : 
`$> ./dbus-java-install-script.sh `
`$> mvn clean install`
Alternatively : 
`$> make deps`

After that for launching with infrastructure extension only :
`$> mvn exec:java -Dexec.mainClass="org.o.erocci.backend.BackendDBusService"`

For usage with docker schema :
`$> mvn exec:java -Dexec.mainClass="org.o.erocci.backend.BackendDBusService" -Dexec.args="docker"`

**Comment by cgourdin** [comment] 2016-03-31 11:55
I will close this issue when Clouddesigner have external repository and i migrate this to gradle.

**Comment by jeanparpaillon** [comment] 2016-07-05 12:39
I suppose you should close this bug as maven local deps are managed with pom.xml:
Install deps with 'mvn initialize'

**Closed** 2016-07-18 13:29 UTC
